### ISSUE TITLE
关于组件化启动模式

### ISSUE THREAD

**Issue by zhuozp** [luckybilly/CC#101]
CC框架中存在不能指定以什么启动方式启动activity，建议可以添加个参数，让调用者可以设置启动模式，毕竟实际复杂业务中可能还是存在需要设置启动模式这种情况的吧。

**Comment by zhuozp** [comment]
CC框架中存在不能指定以什么启动方式启动activity，建议可以添加个参数，让调用者可以设置启动模式，毕竟实际复杂业务中可能还是存在需要设置启动模式这种情况的吧。

**Comment by luckybilly** [comment]
@zhuozp 
CC的组件调用不是仅仅用作activity跳转，而是一次服务调用，为了activity跳转而在api层面专门设计一个方法不大合适
服务的调用方和提供方根据约定（协议）来传递参数和返回值
实现你的这个需求可以将flag值作为参数传递给组件，在组件中startActivity时通过addFlags应用此flag值即可
