### ISSUE TITLE
1.1.0 版本   该Apk 中的Broadcast Receiver组件开启了导出权限，存在组件导出风险。

### ISSUE THREAD

**Issue by Aarthas** [luckybilly/CC#103]
安全检测的时候发生如下情况
1.1.0 版本  该Apk 中的Broadcast Receiver组件开启了导出权限，存在组件导出风险。
[文件]：
AndroidManifest.xml
[代码]：
<receiver android:name=com.billy.cc.core.component.ComponentBroadcastReceiver android:process=:cc>             <intent-filter>                 <action android:name=cc.action.com.billy.cc.libs.component.REMOTE_CC/>                 <action android:name=com.broadlink.auxair.cc.action.REMOTE_CC.awake/>             </intent-filter>         </receiver>

可否单独配置

**Comment by luckybilly** [comment]
先回答你的问题是“可否单独配置”，答案是：可以在打正式包之前在主app module/AndroidManifest.xml中复写该Broadcast Receiver的配置，设置exported="false"。因为正式包是不需要跨app调用组件的，所以没有其它影响。

其实，只要在打正式包时没有打开跨app组件调用（`CC.enableRemoteCC(true)`），ComponentBroadcastReceiver 虽然能接收到外部发的广播，但不会响应，没有安全问题。

![image](https://user-images.githubusercontent.com/4155835/52772955-c9b60680-3074-11e9-8188-7b9ef573dc40.png)


建议尽早按照[升级指南](https://luckybilly.github.io/CC-website/#/1.x_to_2.x)升级到最新版。需要做的也只是将原来的cc-settings.gradle换成cc-settings-2.gradle, 组件的定义及调用都是向下兼容的。
