### ISSUE TITLE
我想问一下问题，组件ActivityA如何添加布局，好像生成不了R文件

### ISSUE THREAD

**Issue by yuanyaozu2017** [luckybilly/CC#109]

**Comment by luckybilly** [comment]
组件内部的开发与是否组件化没有关系，R文件未生成可能是xml文件解析出错，请检查该module下的所有xml文件，建议百度一下具体原因，例如：https://blog.csdn.net/zfan93/article/details/51279224

**Comment by yuanyaozu2017** [comment]
xml文件没问题，只是一个简单的线性布局而已，不过刚刚把组件编译了一遍，然后有报错，把报错解决了，这个资源文件id的问题就解决了，估计是项目是一直没有编译得过的原因吧，感谢大神分享，我在尝试运用这个框架搭建一个简单的app。
