### ISSUE TITLE
有个问题，组件的资源id和主app的资源id能不能一样，现在我的组件有一个布局名称和主app的是一样的，从主app跳转到组件后发现，两个界面一样，我怀疑组件复用了主app的界面了

### ISSUE THREAD

**Issue by yuanyaozu2017** [luckybilly/CC#110]

**Comment by luckybilly** [comment]
不能一样
这一点是跟非组件化开发时一样的，一般建议使用`resourcePrefix`来进行限制

**Comment by yuanyaozu2017** [comment]
好的，反馈个问题，说明文档https://luckybilly.github.io/CC-website/#/integration-create-component在网页上查看的时候不能滑动查看，交互有问题

**Comment by luckybilly** [comment]
在chrome上开发的，其它浏览器暂时没有做适配，可以用chrome浏览器查看

**Comment by luckybilly** [comment]
safari也可以

**Comment by yuanyaozu2017** [comment]
ok，谢谢！
