### ISSUE TITLE
过时的 Api：variantOutput.getProcessManifest() 

### ISSUE THREAD

**Issue by ShelbyYu** [luckybilly/CC#119]
在同步的时候，会有警告提示：WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.

过时的 Api 是 ManifestGenerator  类里面使用了 processManifest 方法，应使用 processManifestProvider。希望更新吧，有强迫症的人，不能容忍提示 Warning。

**Comment by luckybilly** [comment]
@ShelbyYu 有兴趣的话，提个PR吧

**Comment by luckybilly** [comment]
@ShelbyYu cc-register 1.1.2已优化
