### ISSUE TITLE
cc请求返回code -5，找不到组件

### ISSUE THREAD

**Issue by Ccixyj** [luckybilly/CC#122]
修改组件下debug目录下的类后，再次跑cc所有请求返回code -5。初步调查发现component manager下static块未注入icomponent的子类。

**Comment by zhangkangbin** [comment]
class 缓存问题，我已经修改了。我验证一下提交过来。可以帮忙验收一下？

**Comment by Ccixyj** [comment]
> class 缓存问题，我已经修改了。我验证一下提交过来。可以帮忙验收一下？
好的

**Comment by Ccixyj** [comment]
> class 缓存问题，我已经修改了。我验证一下提交过来。可以帮忙验收一下？

好的

**Comment by ervinsae** [comment]
我也碰到这个问题，build-clean一下就OK了，但是再run就会报错code=-5，找不到组件

**Comment by zhangkangbin** [comment]
升级到 cc-register 版本 到 cc-register 1.1.1

**Comment by Ccixyj** [comment]
> 升级到 cc-register 版本 到 cc-register 1.1.1

好了
