### ISSUE TITLE
在gradle5.2版本中编译错误

### ISSUE THREAD

**Issue by longyuan5** [luckybilly/CC#123]
BUILD FAILED in 8s
ERROR: Cause: tried to access method org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V from class org.gradle.api.plugins.AndroidMavenPlugin$8

**Comment by luckybilly** [comment]
是在将CC源码导入Android studio时报错的吗？导入源码时，请保持使用源码中的gradle版本。

这个报错是由android-maven-gradle-plugin与gradle版本的兼容性问题导致的，解决办法是修改以下2处：

1. CC/bintray.gradle：从第57行到最后以后的代码全部注释掉
2. CC/cc-register/build.gradle：启用被注释的第42行代码`//apply plugin: 'maven'` -> `apply plugin: 'maven'`

改完即可正常编译
