### ISSUE TITLE
1.x版本和2.x版本可以分为两个分支，现有的目录有点乱。

### ISSUE THREAD

**Issue by 1799941440** [luckybilly/CC#125]

**Comment by luckybilly** [comment]
现有的目录下，只有1个文件（`cc-settings.gradle`）是为了兼容使用老版本的用户而保留下来的（文件内有注释，[CC文档](https://luckybilly.github.io/CC-website/#/integration)中也有特别说明），其它的所有文件都是最新版的代码。建议详细阅读文档。

不知道你说的乱指的是什么？

**Comment by 1799941440** [comment]
我认为应该需要将cc和cc-register和demo分为三个仓库，demo再导入cc和cc-register

**Comment by luckybilly** [comment]
统一放在一个仓库更利于用户查看和理解，源码是开放出来供用户查看的，使用的时候通过maven依赖jcenter中的包就行。
而且分仓库的话代码维护管理成本更高

**Comment by 1799941440** [comment]
了解了：）
