### ISSUE TITLE
project.apply plugin: 'cc-register' 出错

### ISSUE THREAD

**Issue by zzmzou** [luckybilly/CC#127]

**Comment by zzmzou** [comment]
不知道为何一添加了 cc-register就汇报错:
Android Gradle plugin 3.4.0 must not be applied to project 'G:\Android\CodeRepository\ZProject\02Common\Libs\lib_base' since version 3.4.0 was already applied to this project

**Comment by luckybilly** [comment]
我试的没有问题的哦。。。

截图：
![image](https://user-images.githubusercontent.com/4155835/56671006-6a184f00-66e6-11e9-9754-590750d689b3.png)

**Comment by zzmzou** [comment]
刚对比了下我在组件上添加就会出我说的问题，然后我去掉apply plugin: 'com.android.library' 就可以了。

apply from: rootProject.file('cc-settings-2.gradle')
//apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

请问是不是凡是组件都不需要添加'com.android.library'，因为cc-register已经包含了？
