### ISSUE TITLE
主module组件没有注册

### ISSUE THREAD

**Issue by GoAheadComeOn** [luckybilly/CC#129]
主module里面组件有时候不能注册，有时候可以注册，场景为主module Activity->moduleB Activity->主module Activity(立马关闭moduleB Activity)，如果不立马关闭moduleB Activity可以正常跳转，如果立马关闭moduleB Activity则有时不能正常跳转

**Comment by zhangkangbin** [comment]
cc-register 用1.0.8的，cc-register 1.0.9主module扫描有bug.
