### ISSUE TITLE
MIUI9 android 8.0 不能启动

### ISSUE THREAD

**Issue by huclengyue** [luckybilly/CC#13]
单独以app运行时的组件，在android8.0 上不能启动，设备是MIX2 MIUI9，单独安装的app已经打开一次了。还是不行，提示指定的ComponentName没有找到

**Comment by luckybilly** [comment]
单组件运行调试的时候最好给对应的app赋予自启动权限
顺便说一句:跨app调用仅在开发时使用，正式发布时建议调用CC.enableRemoteCC(false)来显式地关闭跨app调用

**Comment by huclengyue** [comment]
已经给了自启动权限了。在4.4上测试正常的。

**Comment by NightFarmer** [comment]
是的  小米4S无法启动   MIUI9 Android7.0

**Comment by docwei2050** [comment]
红米5PLUS  miui9.6   7.1.2系统无法跨app调用，，，华为7.0是可以的

**Comment by live17909** [comment]
解决了吗？8.0份额会慢慢增加的

**Comment by luckybilly** [comment]
@huclengyue @ysnows @NightFarmer @docwei2050 @live17909 
进程间通信的方案已调整，已经不用广播+service+socket的方式通信了，并且支持app内部进程间组件调用。
目前主体功能开发基本完成，等完善自动注册插件之后即可开放测试（打算从[AutoRegister](https://github.com/luckybilly/AutoRegister)克隆出来给CC做一个定制版的插件，实现一些CC专用的功能），可在[dev_multiprocess分支](https://github.com/luckybilly/CC/tree/dev_multiprocess)抢先体验

**这个问题只是在开发调试的环境下跨app调用组件才会出现，不会影响正式产品的使用，由于跨进程通信的方案正在调整，暂不考虑修复这个问题。**
多进程版本发布后就不存在这个问题了。
建议开发者暂时使用8.0以下的设备进行跨App组件调用的调试工作，给大家带来的不便深感抱歉。

**Comment by 15115464469** [comment]
允许应用自动启动就可以，Mi8 8.1测试通过！

**Comment by luckybilly** [comment]
@huclengyue  @ysnows @NightFarmer @docwei2050 @live17909 @15115464469 
CC 2.0.0已发布在[dev_multiprocess分支](https://github.com/luckybilly/CC/tree/dev_multiprocess)上了，待文档完善后正式发布。
[更新日志](https://github.com/luckybilly/CC/blob/dev_multiprocess/docs/ChangeLog.md)
[升级指南](https://github.com/luckybilly/CC/blob/dev_multiprocess/2.0%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97.MD)

**Comment by luckybilly** [comment]
新版本已发布到了master分支，wiki及相关文档已更新
