### ISSUE TITLE
错误: 编码GBK的不可映射字符

### ISSUE THREAD

**Issue by yunxingyu** [luckybilly/CC#130]
导入最新工程，错误: 编码GBK的不可映射字符

**Comment by luckybilly** [comment]
兄弟，信息太少，没办法帮你啊
把你的环境列一下吧，在说一下在什么情况下报的错，最好截图贴一下

**Comment by yunxingyu** [comment]
> 兄弟，信息太少，没办法帮你啊
> 把你的环境列一下吧，在说一下在什么情况下报的错，最好截图贴一下

今天导入的整个工程，项目无法编译成功，cc项目下的java文件，有很多带中文注释的，都会有“错误: 编码GBK的不可映射字符”错误，按照网上的说法在build.gradle加入
//指定编译的编码
tasks.withType(JavaCompile){
    options.encoding = "UTF-8"
}
但是问题依旧，这应当是一个常见问题，想好好学习CC，项目没法编译，也不能消除所有注释，求高手指点。

**Comment by luckybilly** [comment]
CC的源码是UTF-8编码的，请设置一下你的android studio字符编码环境，[参考](https://blog.csdn.net/jun_tong/article/details/81062125)

**Comment by whitestarlau** [comment]
> 
> 
> CC的源码是UTF-8编码的，请设置一下你的android studio字符编码环境，[参考](https://blog.csdn.net/jun_tong/article/details/81062125)

链接中的方法没有用，问题依旧存在，不是代码问题，而是注释生成javaDoc过程中的问题。目前我还未找到解决办法。

**Comment by whitestarlau** [comment]
![javadoc](https://user-images.githubusercontent.com/9989324/61938459-b912a080-afc3-11e9-803e-7d452c7030f9.png)
补充一下图片。

**Comment by whitestarlau** [comment]
找到了解决办法，在build.gradle中加入：

```
tasks.withType(Javadoc) {
    options.encoding = 'UTF-8'
}

```
有点摸不着头脑，真的只有少数几个人遇到这种问题么？

**Comment by whitestarlau** [comment]
找到了一个办法，在相应的模块的build.gradle中加入如下配置：

> tasks.withType(Javadoc) {
>     options.encoding = 'UTF-8'
> }

可能make通过。不是很理解，真的只有少数几个人遇到了这种问题么。

**Comment by Ccixyj** [comment]
我也遇到
