### ISSUE TITLE
addComponent  maven 方式依赖具体是怎么使用？

### ISSUE THREAD

**Issue by RFlame** [luckybilly/CC#131]
我有的module上传maven后，需要以什么方式依赖进来？

**Comment by RFlame** [comment]
这些上传的module是其他项目里的，需要引入到基于CC框架的项目里，需要怎么引入？

**Comment by luckybilly** [comment]
addComponent 'module_name_or_any_other_word', 'your.pkg.name:your-artifact-name:1.1.0'
第一个参数：作为这个组件module的标识，可以为对应module的名称，也可以是一个任意值
第二个参数：指向maven依赖

**Comment by luckybilly** [comment]
[demo/build.gradle](https://github.com/luckybilly/CC/blob/a57c1d67df98cd2fb3f1156918af32ad7e669f16/demo/build.gradle#L62)中有注释详细说明

[CC文档: 集成CC step2:创建组件 第1.5节](https://qibilly.com/CC-website/#/integration-create-component) 也有明确说明哦

**Comment by RFlame** [comment]
懂了，多谢
