### ISSUE TITLE
IComponent有生命周期么

### ISSUE THREAD

**Issue by RFlame** [luckybilly/CC#137]
在跨模块调用网络接口时，在IComponent实现内里调用一些网络接口，怎么管理生命周期，防止内存泄露？

**Comment by Ccixyj** [comment]
你可以根据请求的callId在合适时机取消吧。同时也有
`CC.Builder cancelOnDestroyWith(Activity activity) `
`CC.Builder cancelOnDestroyWith(Fragment fragment) `
这两个方法
