### ISSUE TITLE
onCall方法中true和false必须与CC调用的异步同步相对应吗

### ISSUE THREAD

**Issue by tangdekun** [luckybilly/CC#138]
// false: 组件同步实现（onCall方法执行完之前会将执行结果CCResult发送给CC）
// true: 组件异步实现（onCall方法执行完之后再将CCResult发送给CC，CC会持续等待组件调用CC.sendCCResult发送的结果，直至超时）

这里的同步和异步与CC异步或同步调用方法一致吗

我异步调用一个方法，onCall返回值是false，这样可以吗

**Comment by luckybilly** [comment]
[文档](https://qibilly.com/CC-website/#/cc-functions)中有说明哦：调用方式不受实现方式的限制（例如:可以同步调用另一个组件的异步实现功能。注：不要在主线程同步调用耗时操作）

onCall方法的返回值只跟是否异步实现有关，调用方可以根据具体场景使用同步或异步方式调用所有组件，无需关心它是如何（同步 or 异步）实现的
