### ISSUE TITLE
Android3.4下无法编译通过

### ISSUE THREAD

**Issue by kigkrazy** [luckybilly/CC#139]
## 环境信息
* AS版本信息如下：
![image](https://user-images.githubusercontent.com/11622206/58865922-03755080-86ea-11e9-858f-cc642b5a2954.png)
* 系统windows 
* NDK版本：`19.2.5345600`

### 1. 代码导入报错如下：
![image](https://user-images.githubusercontent.com/11622206/58865950-1720b700-86ea-11e9-9b69-70294df8dd40.png)
### 2. 点击更新`Upgrade plugin to version 3.4.0 and sync project`，升级gradle版本到3.4
```
ERROR: Cause: tried to access method org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V from class org.gradle.api.plugins.AndroidMavenPlugin$8
```
#### 3.2. `CC/bintray.gradle`中注释掉如下内容
```
apply plugin: 'maven'
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: uri('../repo-local')) //deploy到本地仓库
            pom.groupId = publishedGroupId
            pom.artifactId = artifact
            pom.version = libraryVersion + '-SNAPSHOT'
        }
    }
}
```
#### 3.3依旧报错
```
ERROR: Cannot add task 'install' as a task with that name already exists.
```
### 4. 注释掉`CC/cc-register/build.gradle`中的`apply from: rootProject.file('bintray.gradle')`
报错如下
```
ERROR: Could not get unknown property 'GradleVersion' for project ':demo' of type org.gradle.api.Project.
```

============================================
以上是我报错处理，请问哪里有问题吗， `AS3.4`编译不过问题。

**Comment by kigkrazy** [comment]
以下方案测试通过，高版本AS朋友可以参考下。
## AS高版本解决方案

#### 1. 下载代码同步的时候，点击更新`Upgrade plugin to version 3.4.0 and sync project`，升级gradle版本到3.4

#### 2.  注释掉`cc-register/build.gradle`和`cc-register/build.gradle`中`mvn`插件相关内容
注释内容如下：
```
apply from: rootProject.file('bintray.gradle')

apply plugin: 'maven'
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: uri('../repo-local')) //deploy到本地仓库
            pom.groupId = publishedGroupId
            pom.artifactId = artifact
            pom.version = libraryVersion + '-SNAPSHOT'
        }
    }
}
```
#### 3. 解决`GradleVersion`相关警告
找到如下内容

**Comment by lgengsy** [comment]
同样遇到这个问题，主要原因是GradleVersion 这个API在新的版本中废弃了，其实这个地方直接改下成默认是api就行了，不用做判断。
