### ISSUE TITLE
切换libray和application针对manifest修改不生效

### ISSUE THREAD

**Issue by vihuela** [luckybilly/CC#14]
demo中，每次在local.properties 修改配置之后，执行“Refresh all gradle projects”后针对manifest修改偶尔会出现不能修改的情况，demo_component_kt会出现，原理是什么？在什么时候触发修改

**Comment by luckybilly** [comment]
@vihuela 麻烦确认一下AndroidManifest.xml文件的路径是否正确，可以参考demo_b中的路径

如果需要自定义路径，可以将cc-settings.gradle文件下载到工程根目录，可自行修改其中AndroidManifest.xml文件的路径

![image](https://user-images.githubusercontent.com/4155835/38672677-793b3c9c-3e81-11e8-9eed-62f510ccf491.png)

**Comment by vihuela** [comment]
我发现，我的没有debug文件夹，怎么回事？
![_20180412190259](https://user-images.githubusercontent.com/6533060/38673528-27c653e4-3e84-11e8-9ea8-756b287b8a2d.png)

**Comment by luckybilly** [comment]
这个文件夹是手动创建的，用来放置一些仅在调试时才使用到的代码及资源等文件，在发布release时会排除这个文件夹下的文件

**Comment by vihuela** [comment]
我就纳闷，我看了cc-settings.gradle半天，还看了autoRegister源码，整找不到替换修改文件和移动文件的逻辑，是手动创建啊。。。
