### ISSUE TITLE
代码如何获取组件的类型

### ISSUE THREAD

**Issue by vihuela** [luckybilly/CC#141]
是library或application

**Comment by luckybilly** [comment]
没有提供这个功能，请问什么场景下需要呢？组件单独运行或集成打包，外部调用它的代码是一样的，应该不需要判断它的运行类型的。

**Comment by vihuela** [comment]
哈哈，就是某个fragment开放给其它组件，但是这个fragment又提供一些组件调试。。所以希望搞个判断。。

**Comment by luckybilly** [comment]
调试相关的代码建议仿照demo放在debug目录，不污染正式的代码逻辑
