### ISSUE TITLE
组件多了之后，写 xml 的时候卡顿

### ISSUE THREAD

**Issue by wdeo3601** [luckybilly/CC#143]
我们项目里现在划分了7个组件，发现在写 xml 布局的时候，代码提示变得很慢，要卡一会才能出来。我尝试了一下把所有组件移除后，xml 代码提示又变得很快了，然后一个一个引入组件后，又慢慢变卡顿了，这个是什么原因呢？

**Comment by luckybilly** [comment]
这跟CC框架本身无关，亲测二十多个组件的环境下无影响

**Comment by wdeo3601** [comment]
找到问题了。我项目里用到了 `epoxy` 这个框架，在定义它的 `epoxyModel` 的时候用的是自定义 view 的方式，它的写法需要在自定义 view 上加一个注解，而在 AndroidStudio 里边，当带注解的自定义 view 非常多之后，就会导致 xml 编辑器超级卡。所以这个应该算是 google 的 bug..
