### ISSUE TITLE
遇到一个关于数据绑定的问题

### ISSUE THREAD

**Issue by vihuela** [luckybilly/CC#15]
问题是这样的，单独运行，数据绑定没有问题，作为库依赖，数据绑定会失败，具体代码是：
https://gist.github.com/vihuela/05f06193410456f91c59bd4a8821372e/
18行的DataBindingUtil.inflate会执行失败，binding 返回空，暂时未解决

**Comment by luckybilly** [comment]
xml文件名是否重复导致被覆盖？

**Comment by vihuela** [comment]
@luckybilly 文件名都是有前缀的，也加了
apply plugin: 'kotlin-kapt'
与
 kapt "com.android.databinding:compiler:$android_plugin_version"

**Comment by vihuela** [comment]
@luckybilly 看了一圈，数据绑定似乎不支持library中生成绑定对象，具体在DataBinder类源码中73行开始（api26），原本不加kotlin-kapt连编译都不能通过，加了可以通过编译，但是不能用

**Comment by vihuela** [comment]
@luckybilly 问题找到了，但是暂时未解决，看下图，同样是library，箭头指向的是有生成的，但是红叉的是未生成的
![image](https://user-images.githubusercontent.com/6533060/38930012-e46a552a-4340-11e8-87eb-4928feb99335.png)

**Comment by vihuela** [comment]
@luckybilly 找到原因了，图1可以生成绑定对象，图2不能生成绑定对象
![image](https://user-images.githubusercontent.com/6533060/38931676-8f957ee8-4346-11e8-8c4d-dae323fa66c8.png)
![image](https://user-images.githubusercontent.com/6533060/38931695-9faf47f0-4346-11e8-8353-b30913017e0a.png)

**Comment by luckybilly** [comment]
@vihuela  
addComponent是cc-settings.gradle中提供的方法，用于在主app module中依赖组件，其效果是：在编译期才真正添加依赖，编码期间不依赖，从而达到隔离主app module与组件之间的直接代码调用和资源引用的目的。

请问你是在主app module使用组件中的资源(xml)来进行数据绑定吗？

**Comment by vihuela** [comment]
@luckybilly 方便加你qq 或者 wx嘛？我描述的快些，主要问题就是使用addComponent，DataBinderMapper不生成对应的ViewDataBinding

**Comment by vihuela** [comment]
很棒的框架，多谢作者，修改cc.gradle中project.dependencies.add(dependencyMode, project(":$dependencyName"))，第一个参数为'compile'即可解决问题

**Comment by wholwh** [comment]
主App也需要开启
 dataBinding {
        enabled = true
    }
