### ISSUE TITLE
编译后R文件中的资源ID重复。

### ISSUE THREAD

**Issue by GooDong** [luckybilly/CC#151]
问题：basic_lib编译出来的R文件，存在一定概率跟其他moudle的R文件，id值有重叠。导致，加载资源不符合预期。

1.项目用CC重构；
2.项目有一个basic_lib, ext.alwaysLib = true;
3.项目的主moudle - app , ext.mainApp = true
4.项目其他的moudle都依赖 basic_lib；
5.所有的moudle都经过addComponent ， project 加入到app中；

**Comment by GooDong** [comment]
不知道是不是误报。。。。不是百分百确定。。。。

**Comment by luckybilly** [comment]
addComponent最终是调用'api' 或 'compile' 将module添加到app module的dependencies中的，编译效果跟直接使用api添加依赖的效果一致([源码](https://github.com/luckybilly/CC/blob/a57c1d67df98cd2fb3f1156918af32ad7e669f16/cc-register/src/main/groovy/com/billy/android/register/cc/ProjectModuleManager.groovy#L169)]

addComponent的主要作用是代码隔离和方便组件独立运行
