### ISSUE TITLE
多module之间引用问题

### ISSUE THREAD

**Issue by henkun614** [luckybilly/CC#153]
两个module，moduleA和moduleBase，moduleBase用来提供一些基础类，moduleA能不能依赖moduleBase

**Comment by luckybilly** [comment]
@henkun614  请在moduleBase/build.gradle中添加:
```groovy
ext.alwaysLib = true //如果此module原来是一个library，被其它module所依赖，则启用这一行
```

详情请参阅[文档：创建组件](https://luckybilly.github.io/CC-website/#/integration-create-component) 中的2.1节
