### ISSUE TITLE
有几处log不受标志位控制关不掉

### ISSUE THREAD

**Issue by Simon1121** [luckybilly/CC#155]
class SubProcessCCInterceptor implements ICCInterceptor

service.call(remoteCC, new IRemoteCallback.Stub() {
                    @Override
                    public void callback(RemoteCCResult remoteCCResult) throws RemoteException {
                        try {
                            if (CC.VERBOSE_LOG) {
                                CC.verboseLog(cc.getCallId(), "receive RemoteCCResult from process:%s, RemoteCCResult: %s"
                                        , processName, remoteCCResult.toString());
                            }
                            setResult(remoteCCResult.toCCResult());
                        } catch(Exception e) {
                            **e.printStackTrace();**
                            setResult(CCResult.error(CCResult.CODE_ERROR_REMOTE_CC_DELIVERY_FAILED));
                        }
                    }
                });
            } catch (DeadObjectException e) {
                RemoteCCService.remove(processName);
                connectionCache.remove(processName);
                call(remoteCC);
            } catch (Exception e) {
                **e.printStackTrace();**
                setResult(CCResult.error(CCResult.CODE_ERROR_REMOTE_CC_DELIVERY_FAILED));
            }

**Comment by luckybilly** [comment]
@Simon1121 你好，2.1.6版已作了相关优化
