### ISSUE TITLE
安装后有多个APP

### ISSUE THREAD

**Issue by WeiJieJin** [luckybilly/CC#156]
按照文档配置完成后运行有多个App
![image](https://user-images.githubusercontent.com/5318927/66827127-a7b4b100-ef80-11e9-9739-a40947afd2b3.png)

**Comment by luckybilly** [comment]
单组件module独立运行时是单独以app的方式安装运行的，主app module的build.gradle需要设置`ext.mainApp=true`，表示一直以app方式运行。组件module不需要这个设置，可以在android studio上选择该module再点击Run按钮![image](https://user-images.githubusercontent.com/4155835/66881010-f3ef0800-eff7-11e9-817b-80ef3aff0af5.png)可直接以app方式单独运行，在主app编译时组件module会自动作为library被主app依赖。
文档中是有详细说明的，请仔细检查你的步骤，另外可以参考demo的源码。

**Comment by WeiJieJin** [comment]
是按照文档步骤来配置的。在 app module 设置了 ext.mainApp=true 
![image](https://user-images.githubusercontent.com/5318927/66882748-34518480-effe-11e9-890c-2d3afa666f81.png)
组件
![image](https://user-images.githubusercontent.com/5318927/66882698-053b1300-effe-11e9-8878-c314fd720d47.png)
cc-settings-2.gradle
![image](https://user-images.githubusercontent.com/5318927/66882783-53e8ad00-effe-11e9-9b81-1186218856d0.png)

**Comment by WeiJieJin** [comment]
找到原因了。是我在组件的manifest配置了launch
