### ISSUE TITLE
是否考虑支持 Dynamic Feature Module？

### ISSUE THREAD

**Issue by TreyCai** [luckybilly/CC#158]
请问作者是否考虑支持 Dynamic Feature Module？
以及是否考虑根据打包配置切换 `apply plugin: 'com.android.dynamic-feature'` 或 `apply plugin: 'com.android.library'`

**Comment by luckybilly** [comment]
@TreyCai 我这边暂时还没有这方面的需求，也就没有计划去支持，抱歉！
