### ISSUE TITLE
Provider、Activity组件暴露且未加权限

### ISSUE THREAD

**Issue by luwei2012** [luckybilly/CC#165]
如果想要开启多进程能力，AndroidManifest里面就会添加几个export=true的provider，而且无法添加权限限制，这一点目前是否有办法规避呢

**Comment by luckybilly** [comment]
如果没有enableRemoteCC，会[校验uid](https://github.com/luckybilly/CC/blob/368b8dd029b997ee5a36fc3c6e2b51d4fd82021b/cc/src/main/java/com/billy/cc/core/component/remote/RemoteProvider.java#L38)
