### ISSUE TITLE
能不能给一个组件的maven上传示例,我按照平常的配置是不行的

### ISSUE THREAD

**Issue by yizems** [luckybilly/CC#166]
需要将 CC 组件的插件 //apply from: rootProject.file('cc-settings-2.gradle') ,和 project.ext.runAsApp 去掉,手动添加 `com.billy.android:cc:2.1.6` 这个才行,否则总是报错,

来回调又太麻烦了

**Comment by luckybilly** [comment]
@yizems 在maven 打包上传命令中加上参数`-PccMain=noModule `

例如，将module打包aar：
```gradle
//为demo_component_b打aar包
./gradlew :demo_component_b:assembleRelease -PccMain=noModule 
```

参考文档： https://luckybilly.github.io/CC-website/#/support-plugin-hotfix
