### ISSUE TITLE
壳和组件的通信

### ISSUE THREAD

**Issue by weiweiForAndroid** [luckybilly/CC#170]
在壳的gradle 中添加addComponent之后，打包成app运行的时候，壳app里面不能直接使用组件的类，得通过CC来调用，这个调用是通过反射么？组件内部的调用是通过什么方式？

**Comment by weiweiForAndroid** [comment]
在壳的gradle 中添加addComponent之后，打包成app运行的时候，壳app里面不能直接使用组件的类，得通过CC来调用，这个调用是通过反射么？组件内部的调用是通过什么方式？

**Comment by luckybilly** [comment]
@weiweiForAndroid 请移步[CC文档](https://luckybilly.github.io/CC-website/#/article-cc-principle)

**Comment by weiweiForAndroid** [comment]
@luckybilly 可能我说的不太明白。重新理一下就是，编译时壳不能直接使用依赖的组件中的类，得通过CC来调用。那么这个CC调用的原理是什么？ClassLoader 反射调用的？还是别的什么。我才疏学浅，还请明说。

**Comment by luckybilly** [comment]
@weiweiForAndroid 不是反射，用的是编译期字节码操作实现自动注册，还请查阅[CC的原理文档](https://luckybilly.github.io/CC-website/#/article-cc-principle)

另外可以了解一下我的另一个项目：[AutoRegister](https://github.com/luckybilly/AutoRegister)， [原理文档](https://juejin.im/post/5a2b95b96fb9a045284669a9)

**Comment by yizems** [comment]
@weiweiForAndroid 仔细阅读文档每一个字, 相关技术点 ASM 字节码操作框架, gradle transform API, ,IPC AIDL Binder, 序列化, contenProvider cursor 等等;



100多人watch...

**Comment by weiweiForAndroid** [comment]
@luckybilly 那性能上和  直接依赖 有区别么？

**Comment by weiweiForAndroid** [comment]
@luckybilly 
  详细看了文档，文档内是不是只描述了编译速度。运行时的速度上有差异么？和直接依赖调用的那种方式，在项目运行起来的时候，调用性能上有差异没？
