### ISSUE TITLE
android studio3.6.3关于依赖冲突问题

### ISSUE THREAD

**Issue by fade0706** [luckybilly/CC#173]
各个工程都依赖一个了base库，在把android studio 更新到3.6.3后除了主工程外其他工程的类都有红色报错，提示检模块类路径是否缺少依赖或者依赖冲突，但是能正常编译。 
![78547F20-F466-4827-A385-C93759C7408C](https://user-images.githubusercontent.com/13044161/81469997-e78ffe00-921a-11ea-8805-dd23b02b9656.png)

**Comment by fade0706** [comment]
这个图片不显示了，报错信息是
android studio cannot access 'androidx.activity.ComponentActivity' Which  is a supertype of 'com.xxx.mainactivity'.Check your module classpath for missing or conflicting dependencies

android studio cannot access 'androidx.activity.OnBackPressedDispatcherOwner' Which  is a supertype of 'com.xxx.mainactivity'.Check your module classpath for missing or conflicting dependencies

android studio cannot access 'androidx.savedstate.SavedStateRegistryOwner' Which  is a supertype of 'com.xxx.mainactivity'.Check your module classpath for missing or conflicting dependencies

**Comment by fade0706** [comment]
已解决，根据红色报错信息更新依赖的相关库。

**Comment by zcwk** [comment]
有些base库不是自己的不能更新呢，有什么办法不提示这个错误吗

**Comment by fade0706** [comment]
> 有些base库不是自己的不能更新呢，有什么办法不提示这个错误吗

gradle玩的不熟，按道理说你的base的库应该是你自己维护修改的。如果是依赖的一些第三方的库依赖的一些其他库，你可以在本地重新依赖一次这些冲突的库，然后在重新依赖的地方去除重复依赖的库。
再或者一个简单的办法是提交本地代码到远程，回滚as版本并且删除本地项目和项目配置，重新拉去远程代码，但这只是把问题往后推移的办法
