### ISSUE TITLE
有没有用databinding加cc的？DataBinderMapperImpl好像没生成，不知道是怎么回事。

### ISSUE THREAD

**Issue by MrLuo0312** [luckybilly/CC#18]
module中只要apply   @@了cc-settings.gradle这个plugin，
在这个生成类中，
```
DataBinderMapperImpl() {
    addMapper(new com.XXX.DataBinderMapperImpl());
    addMapper(new com.android.databinding.library.baseAdapters.DataBinderMapperImpl());
    addMapper(new com.XXX.baselibs.DataBinderMapperImpl());
  }
```
貌似对应的Mapper没生成出来？导致DataBindingUtil.setContentView()返回为空...

**Comment by spysoos** [comment]
我也尝试在module里使用 databinding 直接报错 Failed resolution of: Landroid/databinding/DataBinderMapperImpl

**Comment by luckybilly** [comment]
是不是跟 [issue#15](https://github.com/luckybilly/CC/issues/15) 一样的问题? 在主app module中使用了组件中的databinding？

**Comment by MrLuo0312** [comment]
是一样的问题，找到解决方法了，谢谢。
