### ISSUE TITLE
google bundle包失效

### ISSUE THREAD

**Issue by swustmuzi** [luckybilly/CC#187]
google bundle包方式未把component打包进来

**Comment by tianshenyi** [comment]
需要修改CC插件源码，我已实现

**Comment by luckybilly** [comment]
与 #188 相同，[解决方式](https://github.com/luckybilly/CC/issues/188#issuecomment-915135938) 为使用命令参数方式构建，如（demo 替换为自己项目主module的名称）：

```
./gradlew :demo:bundleRelease -PccMain=demo
```
