### ISSUE TITLE
我需要打包.aab（Android App Bundle）的包，這個有什麼方法能打包出來嗎

### ISSUE THREAD

**Issue by wyh123965** [luckybilly/CC#188]
打包出來是每個模塊都分開的，有沒有方法能一起打包出來呢

**Comment by hector-lzp** [comment]
./gradlew :demo:bundleRelease -PccMain=demo

**Comment by tianshenyi** [comment]
需要修改cc插件,我已实现

**Comment by luckybilly** [comment]
[解决方式](https://github.com/luckybilly/CC/issues/188#issuecomment-915135938) 为使用命令参数方式构建，如：

```
// demo 替换为自己项目主module的名称
./gradlew :demo:bundleRelease -PccMain=demo
```
