### ISSUE TITLE
autoregister 引入JavaVersion.VERSION_1_8后不能注册的问题（续）

### ISSUE THREAD

**Issue by currer** [luckybilly/CC#2]
但我并未设置
jackOptions {
enabled true
}
仅仅新建了一个module并且在它的gradle配置文件中设置了
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
就找不到了额...

com.android.tools.build:gradle:3.0.1 版本添加 java8,应该默认不打开jack的吧。
  
![image](https://user-images.githubusercontent.com/7821371/34710992-738c4704-f558-11e7-9cf8-49f7cf617cf6.png)

**Comment by luckybilly** [comment]
@currer  已解决，在根目录的build.gradle中将AutoRegister的版本改为1.1.0即可

**Comment by luckybilly** [comment]
AutoRegister后续又有更新，请使用[github首页](https://github.com/luckybilly/CC)上显示的最新版AutoRegister
注：添加此说明是为了避免有人看到这个issue而使用较老的1.1.0版AutoRegister
