### ISSUE TITLE
目前编译并不支持 Instan Run

### ISSUE THREAD

**Issue by spysoos** [luckybilly/CC#20]
java.util.NoSuchElementException |  
-- | --
java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Failed to execute aapt |  
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Failed to execute aapt |  
com.android.ide.common.process.ProcessException: Failed to execute aapt |  
java.util.NoSuchElementException |

**Comment by luckybilly** [comment]
@spysoos  hi，我刚刚在demo上做了下测试，应该是支持Instant Run的。不知道你测试的场景是什么样的？ 要不加QQ群交流一下：686844583

**Comment by spysoos** [comment]
我稍候再试试
