### ISSUE TITLE
跨组件多进程addPara参数为null时，getParaItem时奔溃

### ISSUE THREAD

**Issue by neil-zhao** [luckybilly/CC#23]
提示json解析错误

**Comment by luckybilly** [comment]
谢谢你的反馈，这是一个bug：在跨app调用时传null值的json转换出现问题,转换成了JSONObject.NULL。 仅在跨app调用组件时出现，在app内部调用组件不会出现这个情况。
已在1.0.0版本修复 [#24](https://github.com/luckybilly/CC/pull/24)
