### ISSUE TITLE
实际公司组件化git部署用的哪种方式

### ISSUE THREAD

**Issue by hongxialiu** [luckybilly/CC#28]
你好，麻烦问下，
1.在实际公司组件化git部署用的哪种方式，gitsubmodule,repo,还是直接组件打包aar发布maven然后主项目引用，或者其他方式。最近再纠结选哪种方式。

**Comment by luckybilly** [comment]
这要看项目的具体规模，中小型项目单工程多module就足够了，分多了反而增加代码的管理成本。规模大一些可以考虑submodule和repo

搭建一个maven私服是比较推荐的方案，可以对组件进行版本管理。通过maven进行依赖，由于aar是已经编译过的交付产物，还可以缩短主APP的编译时间。如果项目规模大了，可以分隔成多个android工程。

另外，如果组件对外暴露的服务协议（或接口）未发生变化，配合maven可以在主app module中通过修改版本号做到单组件的版本回滚。

不知道这样是否回答了你的疑问？

**Comment by hongxialiu** [comment]
谢谢
