### ISSUE TITLE
在组件中传递事件

### ISSUE THREAD

**Issue by kakayang2011** [luckybilly/CC#29]
hi，您好，我想问一下CC框架是否能够向组件传递事件？如账号注销事件 该如何传递给各组件？

**Comment by luckybilly** [comment]
@kakayang2011 
首先说明一下，CC采用的是一对一（点对点）的组件间通信策略，一次CC调用只针对一个组件。
并且目前也不打算支持一对多的方式调用组件：让组件的调用更加有针对性，不希望出现像EventBus那样事件满天飞的情况。

你的这个需求可以使用动态组件来实现，步骤如下：

- UserComponent中定义2个actionName: “subscribe”和“unsubscribe”,接收订阅登录状态的组件
- Activity/Fragment在onCreate时创建一个IDynamicComponent实现类
    - 需要注意的是：如果该Activity/Fragment有多个实例，getName()方法中需要为不同的实例返回不同的name
- 通过CC. registerComponent(component)动态注册，
- 并通过CC调用UserComponent的subscribe向登录组件注册监听
- UserComponent内部记录所有注册监听的组件componentName和actionName
- UserComponent登录状态改变时，将通过CC调用所有注册监听的组件将登录状态发送给它们（多次CC）
- Activity/Fragment在onDestroy时通过CC调用UserComponent的unsubscribe进行注销，
- 并调用CC.unregisterComponent(component)注销动态组件

关于你的这个问题，我在上周六（6月9日）爱奇艺技术沙龙介绍的渐进式组件化方案的分享中也有讲到，PPT在CC的QQ交流群的群文件中可以下载到： 686844583， 欢迎加群讨论！

**Comment by kakayang2011** [comment]
@luckybilly 好的 我明白您的思路了，谢谢您哈
