### ISSUE TITLE
不支持3.1.2的编译

### ISSUE THREAD

**Issue by jiyan135960** [luckybilly/CC#31]
再用gradle 3.1.2编译时会报错 各种的android**.jar出错.这时更改为3.0.1进行编译立刻就好,为什么

**Comment by luckybilly** [comment]
是在demo中报错的吗？如果是的话，按照报错的提示在根目录的build.gradle中这样改一下就可以了：
```
    compileVersion = 27
    buildVersion = '27.0.3'
```
如果不是，麻烦贴一下报错的详细日志。

**Comment by jiyan135960** [comment]
@luckybilly 上面就是编译器报出的错误

**Comment by luckybilly** [comment]
@jiyan135960  确定这个报错是CC导致的吗？可以去掉CC试试，看看是不是就没有问题了。
也可以看看是不是[依赖包的问题](https://stackoverflow.com/a/47854225/6587116)

我这边只看到gradle 3.1.2要求把buildToolsVersion升级到27，按照提示改一下版本号就好了
```
Error:The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.2.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```
看你贴出的日志也没有CC和AutoRegister相关的信息。其他人有遇到同样的问题吗？欢迎留言

**Comment by wholwh** [comment]
使用multidex分包试试

**Comment by jiyan135960** [comment]
我用3.1.3没问题,看了下更新日志我怀疑是3.1.2的D8除了问题 
[这是android studio的更新日志](https://developer.android.com/studio/releases/)
其中第二条和第三条
-  Some applications built with D8 crashed on some Verizon Ellipsis tablets.
-  Installation of applications built with D8 failed with an INSTALL_FAILED_DEXOPT error on devices running Android 5.0 or 5.1 (API level 21 or 22).
是不是有可能和这个有关

**Comment by LiWeiQiangAndroid** [comment]
buildVersion在AS3.0以上可以不用配置了
