### ISSUE TITLE
请问cc支持ButterKnife么?

### ISSUE THREAD

**Issue by AndyGood** [luckybilly/CC#35]
你好,读了一下项目,非常感谢开源.我们项目现在使用ButterKnife,请问CC组件化时支持ButterKnife么?

**Comment by luckybilly** [comment]
@AndyGood  支持的，具体做法可以参考: [文章1](https://blog.csdn.net/qq_28774507/article/details/80505002) 、 [文章2](https://blog.csdn.net/Demo006/article/details/80755177)
