### ISSUE TITLE
多组件单独运行时，原本共享的数据如何同步比较好

### ISSUE THREAD

**Issue by LeonXtp** [luckybilly/CC#36]
问题描述：
比如我的moduleA和moduleB，用到了共享的全局变量及持久化数据，两个组件整合运行时，没有问题。
但是现在两个组件单独运行，它们共享的全局变量和持久化数据，就需要做好同步。
如果它们之间有比较大量的这种共享数据，如果每次修改都一个个去手动做同步，工作量不小，维护起来也麻烦，

请问：
有没有比较好的方式解决这个问题？

**Comment by luckybilly** [comment]
@LeonXtp  最好将这种提供公共数据的服务做在组件中，将数据维护在组件内部（不管是在内存中还是持久化），外部通过组件调用获取数据。比如用户登录信息，就放在用户组件中进行维护，登录完了之后供其它组件获取登录用户的信息。
