### ISSUE TITLE
addComponent方法里无法识别module的ext.runAsApp属性

### ISSUE THREAD

**Issue by AndyGood** [luckybilly/CC#38]
![image](https://user-images.githubusercontent.com/6387361/43469161-2481fefa-9518-11e8-9fea-9e0a1fc05322.png)

hi,你好,我尝试在demo_component_a的gradle文件的第一行加了runAsApp=true,之后demo_component_a作为一个独立App是可以编译安装的.但是demo不能,如果没在loca.properties做配置的话会在addComponent方法里,他会把demo_component_a加入到demo依赖中去.
请问componentProject.ext.has('runAsApp'),这个应该怎样拿到值?非常感谢.

**Comment by luckybilly** [comment]
你好，非常感谢你的反馈，这个情况应该是我漏测了，我刚试了一下，确实跟你描述的一样。

原因是: 在`addComponent`里取值时，组件的build.gradle脚本文件还未运行，`runAsApp`还未被赋值，所以`componentProject.ext.has('runAsApp')`为`false`

说明一下：`runAsApp`是CC**早期**使用的一种为组件切换lib/app运行的方式。由于build.gradle会被提交到代码仓库，为了**防止误提交**，从2018-04-06开始，已经不推荐使用`runAsApp`了。
改为：
- 仅在主app module中使用`ext.mainApp = true`来标明当前module为app壳，一直以app方式编译运行
- 所有组件module都通过local.properties来切换是否以app方式编译运行

原本保留`runAsApp`的功能是为了**兼容**一些早期老用户的使用，这次发现了这个问题，我将考虑在后续的2.0版本中**移除**`ext.runAsApp`，统一使用local.properties来切换组件的lib/app运行方式
