### ISSUE TITLE
关于各个模块初始化操作

### ISSUE THREAD

**Issue by zhouzhiguang** [luckybilly/CC#39]
在每个模块里面都有自己的application初始化分模块怎么做

**Comment by luckybilly** [comment]
有以下几种跟初始化相关的措施，根据具体需求可自行决定如何使用：

1. 在CC初始化时执行组件自身的初始化：在IComponent实现类的**无参构造方法中**进行初始化

2. 在组件第一次被调用时执行组件自身的初始化： 在**`IComponent.onCall(cc)`方法中**进行初始化

3. 作为App单独运行时进行第三方库的初始化： 在debug目录创建测试用的Application子类，在`onCreate`方法中进行初始化，仅在以app方式运行时生效，作为组件集成到主app时不会执行

4. 关联`Application`的生命周期初始化：搭自动注册插件的顺风车，仿照`IComponent`实现类的自动注册：
- 创建`IApplication`接口以及接口的管理类
- 接口类及接口管理类放在底层公共库中
- 组件module中实现接口，通过添加auto-register的配置将接口实现类自动注册到管理类中
- 在`自定义Application`的生命周期方法中通过管理类调用实现类的对应方法
