### ISSUE TITLE
独立业务组建之间跳转问题

### ISSUE THREAD

**Issue by liqianjiang** [luckybilly/CC#4]
最核心的问题是怎么在两个独立业务组建间的跳转，比如从ActivityA跳转到ActivityB。

**Comment by luckybilly** [comment]
@liqianjiang  关于CC的实现原理及相关的应用实践可以查看我的掘金系列文章：https://juejin.im/post/5a2b92e4f265da430d57f047

组件间的跳转是组件化框架最基础的功能之一，如果仅仅是想知道如何使用，可以参考demo中的用法：

[MainActivity](https://github.com/luckybilly/CC/blob/master/demo/src/main/java/com/billy/cc/demo/MainActivity.java)演示了如何打开其它组件的activity（包括app内部的组件和跨app的组件）

[ComponentA](https://github.com/luckybilly/CC/blob/master/demo_component_a/src/main/java/com/billy/cc/demo/component/a/ComponentA.java)演示了组件在接受调用时如何打开当前组件的activity

谢谢你的关注！有任何问题欢迎再次提issue

**Comment by liqianjiang** [comment]
已经清楚了，我们项目中用了其他的组建间通信的方式，现在要实现一个外围的路由跳转由后台动态部署的高兼容性方案。有兴趣可以交流，我的qq:755087768。
