### ISSUE TITLE
module_name=true时运行app module时报-5

### ISSUE THREAD

**Issue by DaiFalin** [luckybilly/CC#42]
当module_name=true时，运行app module获取组件失败，code为-5，单独其他module能够成功运行。
当module_name=false时，运行app module成功

**Comment by luckybilly** [comment]
module_name=true时，module_name对应的module需要以app方式安装运行在手机上才能调用到。
在开发调试期间，可以一动一静安装2个app在手机上
动：组件app（单独以app方式编译运行的组件）
静：主app（包含除`单独以app方式运行的组件`之外的所有组件）

主app和组件app之间的相互调用代码不变，CC将自动通过跨app的方式来转发调用请求。（前提是在调试期间通过调用`CC.enableRemoteCC(true)`启用了跨app组件调用功能）

关联issue： [#5](https://github.com/luckybilly/CC/issues/5)
