### ISSUE TITLE
体验了一下新的跨进程交互

### ISSUE THREAD

**Issue by AndyGood** [luckybilly/CC#43]
hi,我拉了您开发分支来体验了一下,发现一个问题:
W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vending/com.billy.cc.core.component.remote.RemoteConnectionActivity}; have you declared this activity in your AndroidManifest.xml?
我在AndroidManifest上看到是有注册的.

**Comment by luckybilly** [comment]
@AndyGood dev_multiprocess分值上更新了2.0版，欢迎继续体验
