### ISSUE TITLE
moudle 直接共享组件的问题

### ISSUE THREAD

**Issue by leojiao123** [luckybilly/CC#44]
有种场景，demoA demoB 以及他们依赖的base ，在base 中定义一个接口 Itest，在demoA中有 Itest 的实现，demoA demoB 在同一个application 中时，demoB 可以获取demoA 中的 Itest 的实现，分别运行时就不行了，这种场景下除了下沉到base 以外还有别的解决方案吗

**Comment by luckybilly** [comment]
感觉你说的属于路由方案中的思路，按照CC组件总线的思路组件之间应该是传递bean，类似于http请求。
组件总线方案的思路中，业务逻辑应该在组件内部实现，只接收请求参数并返回执行结果，不需要传递业务接口实现类。

**Comment by leojiao123** [comment]
好的
