### ISSUE TITLE
多个apk之间要访问相同SharedPrefence有方法吗？

### ISSUE THREAD

**Issue by xiongtingjin** [luckybilly/CC#46]

**Comment by luckybilly** [comment]
CC没有提供这样的功能，在CC的设计思想中是不推荐这么做的，应该将对SharedPrefence的操作封装成组件的调用暴露给其它组件。
如果你确实有这种多apk之间访问相同SharedPrefence的需求，也是有办法的，可以了解一下sharedUserId和createPackageContext相关的知识
