### ISSUE TITLE
每次更改module为app模式运行，都需要clean一次才能运行成功？

### ISSUE THREAD

**Issue by m4coding** [luckybilly/CC#47]
每次更改module为app模式运行，都需要clean一次才能运行成功的，有没有什么可以解决的办法？

**Comment by luckybilly** [comment]
@bypain 请留意一下demo中的demo_component_b/src/main/debug文件夹，独立运行时，若此文件夹中有manifest文件，则读取这个manifest文件，否则读取默认的manifest

<img width="300" src="https://user-images.githubusercontent.com/4155835/45744766-e5d28a80-bc31-11e8-98af-a29d4448f47e.png" />
<img width="800" src="https://user-images.githubusercontent.com/4155835/45744861-1ca8a080-bc32-11e8-8547-78588f4fbf7b.png" />

**Comment by luckybilly** [comment]
新版已正式发布了

**Comment by yhxxxbl** [comment]
请问这个问题最后是怎样解决的呢，我们的APP使用增量编译 用自己写的批处理文件打包App 现在遇到的问题就是不能灵活的切换组件是否被打包进主App

**Comment by luckybilly** [comment]
@yhxxxbl 跟当前issue主题不一样时，麻烦请新建一个issue提出问题。

并注明一些关键信息，例如：当前使用的版本号，出问题的前置操作步骤和出问题所在的步骤，并讲明问题的特征。
