### ISSUE TITLE
java.lang.OutOfMemoryError 华为手机7.0系统部分手机

### ISSUE THREAD

**Issue by hkstar** [luckybilly/CC#48]
java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Out of memory

java.lang.Thread.nativeCreate(Native Method)
多次调用会创建很多线程

**Comment by luckybilly** [comment]
实现组件时，请确保会调用`CC.sendCCResult(...)`将结果返回给调用方
请检查一下代码，是不是异步调用的组件中没有调用`CC.sendCCResult(...)`，那样的话调用方启动的线程将不会结束。
