### ISSUE TITLE
下载Demo后运行，ComponentB组件里的内容不能打开，返回-5

### ISSUE THREAD

**Issue by ysnows** [luckybilly/CC#5]
![image](https://user-images.githubusercontent.com/11255869/36831525-06dd72bc-1d63-11e8-94fc-5b1bf9a95076.png)

**Comment by luckybilly** [comment]
@ysnows  为了同时演示app内部调用和跨app组件调用，demo中包含了demo_component_a，demo_component_b是单独作为app运行的。

所以需要同时安装2个apk到设备上，并且由于跨组件通信采用了广播，由于系统限制，你需要先启动一次demo_b这个app，然后才能在demo中调用到ComponentB。

PS: 之所以这样做，是为了解决单组件直接跨app与主工程进行组件调用的问题，从而达到从一开始进行组件化改造就可以享受到单组件独立运行秒编译的好处，无需与任何其他组件一起打包运行。

欢迎加qq群交流： 686844583

**Comment by wu1178279937** [comment]
@ysnows  在小米的手机上，同时安装了两个app,并打开了Component_b ,依然结果code 也是 -5

**Comment by luckybilly** [comment]
@wu1178279937 小米手机上可以在应用设置页面给Demo_B赋予自启动权限

**Comment by 362200981** [comment]
依赖地址在哪儿啊？难道必须从demo里把CC的lib拷贝过来才能用啊？
