### ISSUE TITLE
可以跟dagger2 一起使用吗

### ISSUE THREAD

**Issue by xwlichen** [luckybilly/CC#50]

**Comment by luckybilly** [comment]
可以的，只不过在组件化架构下实施起来跟非组件化架构有些不太一样。 这里给你找下参考文章，希望对你有所帮助： 

- [组件化架构Dagger2无缝连接开发](https://www.jianshu.com/p/0e8fd44fb1b8)
- [Android 模块化探索和实践（2）：Dagger2实现模块化（组件化）](https://www.jianshu.com/p/581a7d8fc35a)
