### ISSUE TITLE
主APP与组件之间值传递

### ISSUE THREAD

**Issue by zjgit** [luckybilly/CC#59]
比如：我在APP这个主工程的MainActivity中调用了ComponentA组件中的ActivityA，采用String callId = CC.obtainBuilder("ComponentA").build().callAsync(new IComponentCallback(){...})这种方式，在ComponentA中拦截到并CC.sendCCResult(cc.getCallId(), CCResult.success())处理，那么主APP中立即会在Callback中得到结果，这个OK。但是，现在是这样一个场景：我需要在ActivityA销毁或者点击某个地方触发的事件的时候，把数据回传到MainActivity，并且MainActivity中有相应的方法接收到这个传值再去做其他事。请问下这个该怎么写？

**Comment by luckybilly** [comment]
说明一下，CC是一对一的调用和返回，如果需要多次回调，请使用动态组件（实现IDynamicComponent接口），动态组件的使用类似于android原生的动态广播

**Comment by guozhiqiang123** [comment]
@luckybilly 请问动态组件（IDynamicComponent）该怎么使用啊，有使用文档吗

**Comment by luckybilly** [comment]
国庆节我找时间提供demo代码，并且完善2.0相关的文档，敬请关注！
PS：watch本项目会第一时间收到github上更新的提示哦

**Comment by luckybilly** [comment]
@guozhiqiang123 动态组件的demo代码已经有了：在MainActivity监听登录用户信息
