### ISSUE TITLE
默认超时是多久

### ISSUE THREAD

**Issue by Aarthas** [luckybilly/CC#61]
参考你的《实现登录成功再进入目标界面功能》代码
login页面没调用 CC.sendCCResult(callId, result);返回了，默认超时是多久

**Comment by luckybilly** [comment]
若未手动进行超时设置，同步调用的超时时间为2秒，异步调用没有超时时间（也就是不会超时）
超时设置相关的API有：
- setTimeout(long time) //为当前组件调用设置一个超时时间，单位为ms
- setNoTimeout() //指定当前CC不进行超时监控（在主线程同步调用时无效，会自动改成默认的2秒超时）
