### ISSUE TITLE
执行build及其他非assemble/install开头的任务组件不会编译

### ISSUE THREAD

**Issue by LeonXtp** [luckybilly/CC#63]
CC中使用的cc-settings.gradle脚本，里面判断addComponent是否真正需要进行依赖，只使用了assemble和install开头的任务名做过滤，导致我的项目出现了两个问题:

1. 使用gradle build命令打包时，由于被过滤掉了，一些通过addComponent方式依赖的组件不参与编译，打出来的包比正常的包小了4M。

2. 我的项目中集成了tinker，而tinker打补丁的任务是以tinketPatch开头，同样被过滤掉了，导致打补丁报错，大量的类在dex上的分布发生了移动，且有大量的资源文件被删除，其实同样也是上面的问题导致的。

花了我好久才找到问题所在，现在我是修改了那个正则表达式解决上面的问题。
但这应该算是CC的一个缺陷。

**Comment by luckybilly** [comment]
嗯，确实存在你说的问题，已经在新版本修复了，感谢你的支持和反馈！
