### ISSUE TITLE
使用2.0以上的cc，安装主module，手机出现了两个主module的图标（两个同名APP），删除一个，另一个也没了，请问这是怎么回事？

### ISSUE THREAD

**Issue by HeYongRui** [luckybilly/CC#65]
使用2.0以上的cc，安装主module，手机出现了两个主module的图标（两个同名APP），删除一个，另一个也没了，请问这是怎么回事？而且，其中一个是正常的主module功能，另一个打开直接就是组件module的页面。

**Comment by luckybilly** [comment]
@HeYongRui  请参考[ issue #53 ](https://github.com/luckybilly/CC/issues/53)
