### ISSUE TITLE
组件内初始化

### ISSUE THREAD

**Issue by shingohu** [luckybilly/CC#67]
在开发时,很多组件都需要提前在Application中进行初始化,正常在Application的onCreate中通过CC去调用各个组件来初始,但是这种方式在没增加一个需要初始化的组件的时候都需要去改动Application,如何能做到不修改Application中的代码,达到统一初始化的效果

**Comment by luckybilly** [comment]
这两种方式你选一种吧：
1. 在IComponent实现类中初始化
	1.1 在组件类的无参构造方法中初始化
	1.2 在组件类的onCall方法第一次被调用时初始化
2. 使用cc-register自动注册功能实现（类似于IComponent的自动注册）：将组件初始化工作抽象出一个接口来，通过自动注册来统一调用接口实现类的初始化方法

**Comment by luckybilly** [comment]
这里更详细[#94](https://github.com/luckybilly/CC/issues/94)
