### ISSUE TITLE
主模块使用多进程时，运行主App出现崩溃

### ISSUE THREAD

**Issue by LittleLiByte** [luckybilly/CC#68]
![image](https://user-images.githubusercontent.com/8263017/46844726-ddbdd300-ce0a-11e8-8796-013e6782e6b0.png)
如图...

其他组件单独运行没有问题，不过整合运行就有问题了。。。

**Comment by heroszcy** [comment]
我也遇到了，有解决方案嘛

**Comment by zhangkangbin** [comment]
#保持实现Parcelable的类不被混淆
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
