### ISSUE TITLE
关于数据库设计

### ISSUE THREAD

**Issue by Rabtman** [luckybilly/CC#7]
首先感谢你的开源！
我在进行组件化拆分的时候，对于数据库的设计存在疑问。
我使用的是Room数据库开发，对其进行组件拆分的时候目前只想到如下方式：
1. 每个组件都维护各自一份db，其表和DAO都定义在各自的组件中，但这样使用的时候每个组件都会存在一个db数据库及实例，感觉存在性能问题。
2. 独立一个数据库模块，只维护一份db，将所有的表及其操作都定义在其中，但这么做，内容都集中在一块了，感觉进行的组件化就有点变味了。
想请问下在配合该框架进行组件拆分的时候，有没更好的数据库拆分方式？

**Comment by luckybilly** [comment]
@Rabtman 由于我们项目中用到数据库的地方比较少，这方面之前没太多考虑，是直接放在各自组件中进行维护的。

刚才找人讨论了一下，相对比较好一点的做法是：
在base库中提供需要跨组件共享数据的db，其它的在各个组件内部维护其自身需要的db

希望对你有帮助！

**Comment by Rabtman** [comment]
感谢你的回答！
这个做法就是类似于我在1中所说，受Room这个注解型的数据库限制，使用起来每个组件中就会都维护一个db实例。
再请问下，如果是放在各自组件中维护的话，你们是采用了哪款第三方库，还是说是自己进行的sqlite的封装？

**Comment by luckybilly** [comment]
@Rabtman 我们是自己封装的sqlite，作为基础库供业务组件依赖。
Room我没有用过，不知道是否也可以这样封装。

**Comment by Rabtman** [comment]
明白了，感谢你的耐心解答
