### ISSUE TITLE
addParam() 参数可否增加bundle的支持

### ISSUE THREAD

**Issue by Aarthas** [luckybilly/CC#71]
比如
Bundle bundle = new Bundle();
bundle.putInt("a",1);
CC.obtainBuilder(CCContant.MainComponent).addBundle(bundle).build().call();

组件里
 @Override
    public boolean onCall(CC cc) {
 ...
       Bundle bundle =  cc.getBundle();
...
    }

**Comment by luckybilly** [comment]
需要加这个的理由是什么呢？

现在已经支持传递bundle了：
```
//添加bundle参数
addParam(key, bundle)
//取出bundle参数
Bundle bundle = cc.getParamItem(key, defaultValue);
```

**Comment by MrKangWen** [comment]
也许这样改造起来，少更改一点。

**Comment by luckybilly** [comment]
@Aarthas @MrKangWen 2.1.2增加了这一点的支持，请查看[更新日志 ](https://github.com/luckybilly/CC/blob/master/docs/ChangeLog.md)
