### ISSUE TITLE
跨app，异步调用不设置回调，如何取消

### ISSUE THREAD

**Issue by zhaolijunstar** [luckybilly/CC#86]
![image](https://user-images.githubusercontent.com/27919193/49695233-efd1ad00-fbd2-11e8-88e5-91d4e5014a7a.png)
如果是异步调用且未设置回调，callbackNecessary一直是false，if (!cc.isFinished() && callbackNecessary)这个判断永远进入不了，如何去掉本次调用？

**Comment by Ccixyj** [comment]
设置超时或用callid来取消

**Comment by luckybilly** [comment]
@zhaolijunstar 截图中的代码是1.x.x版本的，异步未设置回调的CC调用将不能取消
在2.0.0及以上的版本中可以通过CC.cancel(callId)来取消
