### ISSUE TITLE
设置了noTimeOut，但是报超时-9怎么处理啊

### ISSUE THREAD

**Issue by TJundx** [luckybilly/CC#88]

**Comment by ZhangdroidApp** [comment]
IComponent实现类对应的action返回值来确定是否延时返回结果，你需要排查下返回值是否为false，只有异步调用才需要延时的

**Comment by TanJunDang** [comment]
> IComponent实现类对应的action返回值来确定是否延时返回结果，你需要排查下返回值是否为false，只有异步调用才需要延时的

没有异步调用啊
