### ISSUE TITLE
可否出一套渐进式的教程

### ISSUE THREAD

**Issue by fanqieVip** [luckybilly/CC#97]
如题，像我这种只关注如何使用且为刚接触组件化框架的人其实还不少，我们需要一套渐进式的教程来一步步感受框架的魅力。因为目前的教程，我只能感受到好厉害的样子，其余就没了，有劳大神啦！

**Comment by luckybilly** [comment]
@fanqieVip 新版文档地址：https://luckybilly.github.io/CC-website/

**Comment by fanqieVip** [comment]
感谢大神的回复。
另外我也做了个实验性的组件化框架，大神要是有时间的话，也看一下吧，给我提提改良建议，谢谢啦。
https://github.com/fanqieVip/processroute
