### ISSUE TITLE
对于Gradle版本号4.10.1类似版本号情况 ERROR: Cause: multiple points

### ISSUE THREAD

**Issue by TinloneX** [luckybilly/CC#99]
对于Gradle版本号4.10.1类似版本号情况
def dependencyMode = (project.gradle.gradleVersion as float) >= 4.1F ? 'api' : 'compile'
报错 ERROR: Cause: multiple points，可以如下操作
==》
依据版本大/小于4.1自行更改
def dependencyMode ='api' 
或
def dependencyMode ='compile'

**Comment by zhangkangbin** [comment]
#95
